---

- name: Install Packages
  hosts: 
  - localhost
  become: true
  remote_user: kenny
 
  pre_tasks: 
    - name: Update all repositories
      apt: 
       update_cache: yes 

    - name: Upgrade all packages
      apt: 
        name: "*" 
        state: latest
  
  tasks:
    - name: Installing apt packages 
      package: 
        name: 
          - snapd
          - git
          - google-chrome-stable
          - cifs-utils
          - unzip
          - ack
          - fzf
          - zsh
          - powerline 
          - fonts-powerline
          - python3-pip
          - steam 
          - dnsutils

    - name: installing snap packages
      snap: 
        name: 
          - spotify
          - discord
          - yq

    - name: install vscode
      snap: 
        name: code
        classic: yes

    - name: install neovim
      snap: 
        name: nvim
        classic: yes
